### PR TITLE
Lint using new TypeScript configs from eslint-config-openstax-poland

### PR DESCRIPTION
**Pull request by aiwenar**
Requires openstax-poland/eslint-config-openstax-poland#4.

### CODE REVIEW

**Comment by PiotrKozlowski** [comment]
`yarn lint` is giving me a bunch of errors. Is this because it is still a draft pr or I've missconfigured something?
```
$ eslint --ext .js,.jsx,.ts,.tsx src/

/home/piotr/Dokumenty/github/slate-lists/src/index.ts
   7:27  error  Missing file extension for "./normalize"                                          import/extensions
   8:25  error  Member 'decreaseDepth' of the import declaration should be sorted alphabetically  sort-imports
   8:46  error  Missing file extension for "./transforms"                                         import/extensions
  10:32  error  Missing file extension for "./interfaces"                                         import/extensions
  13:18  error  An interface declaring no members is equivalent to its supertype                  @typescript-eslint/no-empty-interface

/home/piotr/Dokumenty/github/slate-lists/src/interfaces.ts
   7:1   error  Expected multiple line comments instead of a block comment  multiline-comment-style
  12:18  error  Expected a semicolon                                        @typescript-eslint/member-delimiter-style
  24:1   error  Expected multiple line comments instead of a block comment  multiline-comment-style
  29:23  error  Expected a semicolon                                        @typescript-eslint/member-delimiter-style

/home/piotr/Dokumenty/github/slate-lists/src/normalize.ts
   5:35  warning  'Text' is defined but never used                     @typescript-eslint/no-unused-vars
   7:32  error    Missing file extension for "./interfaces"            import/extensions
   9:16  warning  Missing return type on function                      @typescript-eslint/explicit-function-return-type
  39:1   error    This line has a length of 83. Maximum allowed is 80  max-len

/home/piotr/Dokumenty/github/slate-lists/src/transforms.ts
    5:1   error    This line has a length of 92. Maximum allowed is 80                      max-len
    5:49  error    Member 'Node' of the import declaration should be sorted alphabetically  sort-imports
    7:32  error    Missing file extension for "./interfaces"                                import/extensions
   13:23  error    Expected a semicolon                                                     @typescript-eslint/member-delimiter-style
   29:23  error    Expected a semicolon                                                     @typescript-eslint/member-delimiter-style
   35:17  warning  'parent' is assigned a value but never used                              @typescript-eslint/no-unused-vars
   37:25  error    'isComplexBlock' was used before it was defined                          @typescript-eslint/no-use-before-define
   42:13  error    'spansToWrapInList' was used before it was defined                       @typescript-eslint/no-use-before-define
   49:19  error    'startRef' is never reassigned. Use 'const' instead                      prefer-const
   49:29  error    'endRef' is never reassigned. Use 'const' instead                        prefer-const
   54:27  warning  Missing return type on function                                          @typescript-eslint/explicit-function-return-type
   56:1   error    This line has a length of 81. Maximum allowed is 80                      max-len
  100:1   error    This line has a length of 93. Maximum allowed is 80                      max-len

✖ 26 problems (22 errors, 4 warnings)
  11 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by aiwenar** [comment]
I'm not sure. This PR was a draft since openstax-poland/eslint-config-openstax-poland#4 wasn't merged yet and so just running `yarn` would install the old version, but that doesn't appear to be your problem. In any case try removing `node_modules`, reinstalling dependencies, and linting again.

**Comment by PiotrKozlowski** [comment]
I still have the same errors - Previously I've added commit's hash for the `"eslint-config-openstax-poland"`

**Comment by aiwenar** [comment]
After having a closer look those errors are rather strange:

- `@typescript-eslint/member-delimiter-style` reports _Expected a semicolon_, but is configured to use commas or nothing;

- `@typescript-eslint/no-unused-vars` reports _'Text' is defined but never used_ on 5th line of src/normalize.ts, but `Text` isn't used anywhere in that file;

- `@typescript-eslint/explicit-function-return-type` reports _Missing return type on function_ on 54th line of src/transforms.ts, but that line is
 
  ```ts
  const start = startRef.unref()!
  ```

  and the closes functions begin on lines 28 and 94;

- errors are reported for non-TypeScript style lints, which shouldn't happen since TypeScript style config was accidentally not based on primary style config (see openstax-poland/eslint-config-openstax-poland#5).

Just to make sure, what commit were you on when testing?

**Comment by PiotrKozlowski** [comment]
I'm not sure, but I don't see errors anymore¯\_(ツ)_/¯

**Review by PiotrKozlowski — APPROVED** [review]

**Pull request merged**
